apiVersion: v1
kind: Service
metadata:
  name: redes-projeto
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080 # Altere conforme necessário
  selector:
    app: redes-projeto
